### ISSUE TITLE
Use the unittest framework for testing

### ISSUE THREAD

**Issue by josenavas** [Jorge-C/ordination#10]
As it is done in other Knight Lab projects

**Comment by Jorge-C** [comment]
I'm not sure about what you mean. Tests can be run both by nose and
py.test, and not using one is unproductive. nose is already a dependency of
some of the existing lab projects. I'm keeping py.test compatibility
because it is a great test runner (maybe I should raise this in the mailing
list):
- Easy test parallelization with [xdist](http://pytest.org/latest/xdist.html).
  Just run `py.test -n 4` and your tests are using 4 cores.
- In fact, it's even better than that because you can distribute tests via
  ssh to other machines.
- Users don't need to have it installed to run tests because it can
  generate a test runner script.
- Plain `assert x == y` can be used.
- It can run nose tests.

2014/1/15 josenavas notifications@github.com

**Comment by josenavas** [comment]
Since this code is going to be included in bipy, it should follow the standards defined there. Check the [tests](https://github.com/biocore/bipy/tree/master/tests) folders in the bipy repo to see how the unittest framework works. You can also check other projects, as all of them use it.
