### ISSUE TITLE
Rename base.py to ordination.py

### ISSUE THREAD

**Issue by josenavas** [Jorge-C/ordination#7]
Will make the integration into bipy easier.

**Comment by Jorge-C** [comment]
I actually agree that it needs to be refactored, but I don't see how
renaming could help integration.

The idea behind the current approach is that only baseclasses are kept in
`base.py` and each method lives in its own file. This separation doesn't
exist right now because we're at just 3 methods (still, that's ~600 loc),
but that's the way forward when pcoa, etc end up here.

2014/1/15 josenavas notifications@github.com

**Comment by josenavas** [comment]
Got it. I was thinking in including all the methods in a single file, but I see that it can be a mess.

In this case, perform the refactoring that you propose: keep the base classes on base.py (or you may want to include them in `__init__.py`, I've seen this in other projects, and you''ll have this file anyway) and move each method to its own file.
