### ISSUE TITLE
Move the test folder to the base folder

### ISSUE THREAD

**Issue by josenavas** [Jorge-C/ordination#8]
Following standards used in other projects in the Knight Lab

**Comment by Jorge-C** [comment]
The approach of having tests by each module instead of all together in a
different folder has a number of advantages, that seem to become more
important as projects grow, and I guess that's why numpy, scipy,
scikit-learn, ipython... do it like this.
- Code and tests are close: when working on one part of the codebase, tests
  are right there. There's no need to duplicate the package folder structure
  like [this](https://github.com/biocore/bipy/tree/master/tests). Each
  subpackage is self contained.
- It's easier to ship tests, so that users can easily test the package by
  running something like `mypckg.test()`.

2014/1/15 josenavas notifications@github.com

**Comment by josenavas** [comment]
Post a question in the bipy repo. If other developers agree and we end up changing the folder structure just close this issue. If not, make the change. This code is going to be included in bipy, so it should follow the same structure.

Personally, I prefer the directory structure defined in bipy.

**Comment by josenavas** [comment]
It looks like we are going to use this directory structure. Closing the issue.
